apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-library
  description: An example of an API service.

spec:
  type: openapi
  owner: john@example.com
  lifecycle: production
  definition:
    $text: https://github.com/myusko/backstagetest/blob/main/test-oas-api.yaml
