apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-library
  description: An example of a Backstage library.
  annotations:
    backstage.io/techdocs-ref: dir:./

spec:
  type: library
  owner: john@example.com
  lifecycle: experimental
