apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-api
  description: An example of an API service.
  annotations:
    # The annotation is deprecated, we use placeholders (see below) instead, remove it later.
    backstage.io/definition-at-location: 'url:https://github.com/myusko/backstagetest/blob/main/test-oas-api.yaml'

spec:
  type: openapi
  owner: john@example.com
  lifecycle: production
  definition:
    $text: https://github.com/myusko/backstagetest/blob/main/test-oas-api.yaml
